import = [
    "custom.toml"
]

[env]
term = "xterm-256color"

[window]
opacity = 1.00
#blur = true
padding.x = 2
padding.y = 2
decorations = "Full"
startup_mode = "Maximized"

[scrolling]
history = 5000

[font]
size = 15
#normal = { family = "JetBrains Mono", style = "Regular" }
normal = { family = "Roboto Mono", style = "Medium" }
